version: '2.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/syncmate
    ports:
      - "80:80"
    command: bash -c 'python3 manage.py runserver 0.0.0.0:80 & celery -A syncMate worker -P solo --loglevel=info'
    environment:
      - DEBUG=1
      - API_URL=http://184.105.6.196/media/
    depends_on:
      - rabbitmq

  rabbitmq:
    restart: always
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq_config/:/etc/rabbitmq/
    expose:
      - 5672
      - 15672
    environment:
      - RABBITMQ_SCHEMA=amqp
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
