# Generated by Django 3.2.10 on 2023-10-21 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231016_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synctask',
            name='synced_file_path',
        ),
        migrations.AddField(
            model_name='synctask',
            name='synced_file',
            field=models.FileField(default=datetime.datetime(2023, 10, 21, 21, 50, 31, 624888, tzinfo=utc), upload_to='result/'),
            preserve_default=False,
        ),
    ]
