# Generated by Django 3.2.10 on 2023-12-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20231021_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctask',
            name='cloudinary_path',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
